### ISSUE TITLE
cannot access demo.requs.org

### ISSUE THREAD

**Issue by caarlos0** [yegor256/requs#98]
![screenshot from 2015-01-16 16 09 00](https://cloud.githubusercontent.com/assets/245435/5781450/0293b4ce-9d9a-11e4-9f32-6f91ef35807d.png)

**Comment by davvd** [comment]
I'm aware of the task, give me some time to find a developer...

**Comment by davvd** [comment]
@caarlos0 thanks a lot for reporting, **15 mins** added to your acc, pmt ID `AP-4YJ14693HB695020S`

**Comment by atapin** [comment]
Still unresolved?

**Comment by a10zn8** [comment]
Is project still alive?

**Comment by caarlos0** [comment]
🤷‍♂️
